Tên: Nguyễn Minh Quân<br>
MSSV: 20098151

In [1]:
import pandas as pd
import firebase_admin
from firebase_admin import firestore, credentials

cred = credentials.Certificate('iuh-20098151-firebase-adminsdk-wyb05-41ce913fdb.json')
app = firebase_admin.initialize_app(cred)
dbFireStore = firestore.client()

In [2]:
queryResults = list(dbFireStore.collection(u'tbl-20098151').limit(5).stream())
listQueryResult = list(map(lambda x : x.to_dict(), queryResults))
df = pd.DataFrame(listQueryResult)
df

,POSTALCODE,TERRITORY,QTR_ID,CUSTOMERNAME,ORDERDATE,ORDERLINENUMBER,CONTACTFIRSTNAME,SALES,STATUS,PRODUCTLINE,...,MONTH_ID,ADDRESSLINE2,STATE,YEAR_ID,MSRP,CONTACTLASTNAME,CATEGORY,PRODUCTCODE,COUNTRY,QUANTITYORDERED
0,N 5804,EMEA,3,Herkku Gifts,9/3/2004,3,Veysel,8272.34,Shipped,Vintage Cars,...,9,NaN,NaN,2004,168,Oeztan,Furniture,S18_2795,Norway,43
1,97561,NaN,3,Gift Ideas Corp.,9/3/2003,2,Dan,3155.58,Shipped,Motorcycles,...,9,NaN,CT,2003,62,Lewis,Furniture,S18_3782,USA,47
2,2060,APAC,3,"Anna's Decorations, Ltd",9/11/2003,14,Anna,5418.88,Shipped,Classic Cars,...,9,Level 15,NSW,2003,169,O'Hara,Furniture,S18_3232,Australia,32
3,42100,EMEA,2,L'ordine Souveniers,5/10/2005,3,Maurizio,5642.83,Shipped,Planes,...,5,NaN,NaN,2005,118,Moroni,Technology,S700_2834,Italy,41
4,28034,EMEA,4,Euro Shopping Channel,12/2/2003,8,Diego,3930.40,Shipped,Classic Cars,...,12,NaN,NaN,2003,194,Freyre,Furniture,S12_1099,Spain,20

In [4]:
queryResults = list(dbFireStore.collection(u'tbl-20098151').where(u'COUNTRY', u'==', 'USA').stream())
listQueryResult = list(map(lambda x : x.to_dict(), queryResults))
df = pd.DataFrame(listQueryResult)
df

,QUANTITYORDERED,PRICEEACH,TERRITORY,ORDERLINENUMBER,ORDERDATE,CUSTOMERNAME,CONTACTFIRSTNAME,CITY,STATUS,PRODUCTLINE,...,MONTH_ID,ADDRESSLINE2,STATE,YEAR_ID,MSRP,CONTACTLASTNAME,CATEGORY,PRODUCTCODE,COUNTRY,QTR_ID
0,47,67.14,NaN,2,9/3/2003,Gift Ideas Corp.,Dan,Glendale,Shipped,Motorcycles,...,9,NaN,CT,2003,62,Lewis,Furniture,S18_3782,USA,3
1,45,49.81,NaN,12,12/2/2003,Muscle Machine Inc,Jeff,NYC,Shipped,Classic Cars,...,12,Suite 400,NY,2003,50,Young,Office Supplies,S24_1628,USA,4
2,37,100.00,NaN,4,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Ships,...,11,NaN,MA,2003,100,Tam,Technology,S700_3505,USA,4
3,48,42.26,NaN,5,11/4/2004,FunGiftIdeas.com,Violeta,New Bedford,Shipped,Classic Cars,...,11,NaN,MA,2004,50,Benitez,Office Supplies,S24_1628,USA,4
4,47,77.24,NaN,8,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Vintage Cars,...,11,NaN,MA,2003,87,Tam,Furniture,S18_4522,USA,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,20,48.62,NaN,15,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Trains,...,11,NaN,MA,2003,58,Tam,Accessories,S50_1514,USA,4
1000,49,49.28,NaN,6,9/12/2003,Signal Collectibles Ltd.,Sue,Brisbane,Shipped,Vintage Cars,...,9,NaN,CA,2003,44,Taylor,Office Supplies,S24_2022,USA,3
1001,21,64.66,NaN,8,10/10/2003,Corporate Gift Ideas Co.,Julie,San Francisco,Shipped,Motorcycles,...,10,NaN,CA,2003,62,Brown,Furniture,S18_3782,USA,4
1002,41,100.00,NaN,8,1/29/2004,West Coast Collectables Co.,Steve,Burbank,Shipped,Vintage Cars,...,1,NaN,CA,2004,99,Thompson,Furniture,S18_3320,USA,1
1003,50,61.22,NaN,7,5/11/2004,The Sharp Gifts Warehouse,Sue,San Jose,Shipped,Vintage Cars,...,5,NaN,CA,2004,68,Frick,Office Supplies,S32_4289,USA,2

In [5]:
queryResults = list(dbFireStore.collection(u'tbl-20098151').where(u'YEAR_ID', u'==', 2005).where(u'QTR_ID', u'==', 1).stream())
list(map(lambda x : x.to_dict(), queryResults))
df = pd.DataFrame(listQueryResult)
df

,QUANTITYORDERED,PRICEEACH,TERRITORY,ORDERLINENUMBER,ORDERDATE,CUSTOMERNAME,CONTACTFIRSTNAME,CITY,STATUS,PRODUCTLINE,...,MONTH_ID,ADDRESSLINE2,STATE,YEAR_ID,MSRP,CONTACTLASTNAME,CATEGORY,PRODUCTCODE,COUNTRY,QTR_ID
0,47,67.14,NaN,2,9/3/2003,Gift Ideas Corp.,Dan,Glendale,Shipped,Motorcycles,...,9,NaN,CT,2003,62,Lewis,Furniture,S18_3782,USA,3
1,45,49.81,NaN,12,12/2/2003,Muscle Machine Inc,Jeff,NYC,Shipped,Classic Cars,...,12,Suite 400,NY,2003,50,Young,Office Supplies,S24_1628,USA,4
2,37,100.00,NaN,4,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Ships,...,11,NaN,MA,2003,100,Tam,Technology,S700_3505,USA,4
3,48,42.26,NaN,5,11/4/2004,FunGiftIdeas.com,Violeta,New Bedford,Shipped,Classic Cars,...,11,NaN,MA,2004,50,Benitez,Office Supplies,S24_1628,USA,4
4,47,77.24,NaN,8,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Vintage Cars,...,11,NaN,MA,2003,87,Tam,Furniture,S18_4522,USA,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999,20,48.62,NaN,15,11/14/2003,Mini Creations Ltd.,Wing C,New Bedford,Shipped,Trains,...,11,NaN,MA,2003,58,Tam,Accessories,S50_1514,USA,4
1000,49,49.28,NaN,6,9/12/2003,Signal Collectibles Ltd.,Sue,Brisbane,Shipped,Vintage Cars,...,9,NaN,CA,2003,44,Taylor,Office Supplies,S24_2022,USA,3
1001,21,64.66,NaN,8,10/10/2003,Corporate Gift Ideas Co.,Julie,San Francisco,Shipped,Motorcycles,...,10,NaN,CA,2003,62,Brown,Furniture,S18_3782,USA,4
1002,41,100.00,NaN,8,1/29/2004,West Coast Collectables Co.,Steve,Burbank,Shipped,Vintage Cars,...,1,NaN,CA,2004,99,Thompson,Furniture,S18_3320,USA,1
1003,50,61.22,NaN,7,5/11/2004,The Sharp Gifts Warehouse,Sue,San Jose,Shipped,Vintage Cars,...,5,NaN,CA,2004,68,Frick,Office Supplies,S32_4289,USA,2